### ISSUE TITLE
gmake error 2

### ISSUE THREAD

**Issue by redlewel** [tuxxi/masm-unix#1]
I have an issue when trying to build the project:
```
cmake --build build     
yasm: option `--prefix' needs an argument!
yasm: warning: can open only one input file, only the last file will be processed
make[3]: *** [Makefile:50: Along32.o] Error 1
gmake[2]: *** [CMakeFiles/Along32.dir/build.make:70: CMakeFiles/Along32] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/Along32.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

This has been done on Ubuntu 22.04 and Fedora 37 with no luck.  I have all the build requirements installed.  

Anyone run into this before?

**Comment by LianSheng197** [comment]
I'm also on Ubuntu 22.04.3 and I'm getting this error on my machine too.

**Comment by LianSheng197** [comment]
If anyone reads this message, you can skip the yasm version issue for now.

Considering that yasm has been updated since this repo appeared, I suspected that it might be a yasm version issue, so I deleted the original yasm (v1.3.0) that was installed from apt, and compiled and installed it from the v1.2.0 source code.
Here are the commands I used to build yasm v1.2.0.
```bash
# Ubuntu 22.04.3 jammy
# x86_64 Linux 6.2.0-26-generic
wget https://www.tortall.net/projects/yasm/releases/yasm-1.2.0.tar.gz
tar -xzvf yasm-1.2.0.tar.gz
cd yasm-1.2.0/
./configure
make
sudo make install
. ~/.bashrc # Or open a new shell
yasm --version 
# yasm 1.2.0
# Compiled on Sep 18 2023.
# Copyright (c) 2001-2011 Peter Johnson and other Yasm developers.
# Run yasm --license for licensing overview and summary.
```

However, when trying to go back to masm-unix and run `cmake --build build`, the error remains the same.

---- Edit ----
Later I tried to go back to previous versions, because I guessed that maybe the compatibility with OSX caused special problems, but unfortunately none of them worked.
```bash
git checkout HEAD~X # X is the number of commits to go back
```
(Notice: Some earlier versions used `nasm` instead of `yasm`.)

I think it's because the underlying library version doesn't support certain syntaxes anymore, so no matter how much I tried to modify it, I couldn't get it to compile.

Unfortunately, I don't have any experience in writing this kind of project, so I don't know how to fix it. If anyone else has encountered a similar problem, I hope you can leave a comment on how to fix it.

**Comment by rzuckerm** [comment]
I'm seeing the same issue. I have a workaround:
```
sed -i 's/ASMFLAGS = --prefix _/ASMFLAGS = --prefix=_/' src/Along32/src/Makefile
```

However, now I'm seeing this error:

```console
/opt/masm-unix# cmake --build build
Scanning dependencies of target Along32
Along32.asm:141: error: cannot reference symbol `$' in preprocessor
Along32.asm:141: error: non-constant value given to `%assign'
Along32.asm:866: error: undefined symbol `bufferMax' (first use)
Along32.asm:866: error:  (Each undefined symbol is reported only once.)
Along32.asm:992: error: undefined symbol `charVal.B8' (first use)
Along32.asm:1029: error: undefined symbol `xlat.B5' (first use)
Along32.asm:1580: error: redefinition of `xlat'
Along32.asm:1021: error: `xlat' previously defined here
Along32.asm:1598: error: redefinition of `xlat'
Along32.asm:1021: error: `xlat' previously defined here
Along32.asm:1604: error: redefinition of `xlat'
Along32.asm:1021: error: `xlat' previously defined here
Makefile:50: recipe for target 'Along32.o' failed
make[3]: *** [Along32.o] Error 1
CMakeFiles/Along32.dir/build.make:57: recipe for target 'CMakeFiles/Along32' failed
make[2]: *** [CMakeFiles/Along32] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Along32.dir/all' failed
make[1]: *** [CMakeFiles/Along32.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm making a docker image, and I have moved all the way back to Ubuntu 16.04 as the base image. No luck!

**Comment by spersinger** [comment]
I fixed this with my branch. I'm working on trying to merge it. If you want to use my fork for the meantime you can find it at: https://github.com/spersinger/masm-unix

**Comment by bastiel** [comment]
> I fixed this with my branch. I'm working on trying to merge it. If you want to use my fork for the meantime you can find it at: https://github.com/spersinger/masm-unix

I uninstalled yasm and installed nasm (as your fork required), but I'm still getting errors related to yasm when I run `cmake --build ./ `

```
make[3]: yasm: No such file or directory
make[3]: *** [Makefile:50: Along32.o] Error 127
gmake[2]: *** [CMakeFiles/Along32.dir/build.make:70: CMakeFiles/Along32] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/Along32.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```
Keeping both yasm and nasm results in the original error (OP's error).

**Comment by bastiel** [comment]
> I uninstalled yasm and installed nasm (as your fork required), but I'm still getting errors related to yasm when I run `cmake --build ./ `

Some possible progress:

I deleted @spersinger fork and redid the steps included up until `cmake ../`

I went back to the `masm-unix` folder and ran this command: `grep -rnw . -e "yasm"` and one of the results was `./src/Along32/src/Makefile:22:ASM = yasm` 

I edited the file and replaced "yasm" with "nasm" (note: I have no idea if this is appropriate to do - just trying random things here). Then I ran `cmake --build ./` which seemed to have worked. It `Built target objconv` with 100% progress and no errors. 

However, I can't get the last two steps to work: 
```
cd ../src/Along32/src 
sudo make install 
```
It keeps saying `make: *** No rule to make target 'install'.  Stop.`

I'm assuming it's confirmed not installed properly because in VS Code, it will run MASM32 code fine without any libraries, but if you include irvine32.inc or along32.inc, it'll say that the called functions aren't defined. 

It'll also return `code 36`. Not sure if that's a result of configuring MASM to work with Linux or if I did something else wrong.

**Comment by spersinger** [comment]
I did most of that in my fork actually. I changed the makefiles to use nasm. 

On regards to the last step, it is because the version of Along32 provided in tuxxi/masm-unix does not have the correct Makefile. A possible fix is copying the makefile I included that is from an older version of Along32, or editing the makefile to add an install step.

**Comment by aehris-hashami** [comment]
How am I supposed to assemble the code using the make command when its interfering with the original make command? It just says there's no rule to make target, Stop.
